version: "3.11"

services:

# database service
  postgres_db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password123456"
      POSTGRES_DB: "games_db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    restart: always
    networks:
      - custom

# application service
  games_app:
    build: .
    command: bash -c 'while !</dev/tcp/postgres_db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    environment:
      - DATABASE_URL="postgresql+asyncpg://admin:password123456@postgres_db:5432/games_db"
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    networks:
      - custom

networks:
  custom:
    driver: bridge
