version: "3.11"

services:

# database service
  postgres_db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password123456"
      POSTGRES_DB: "games_db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    restart: always
    networks:
      - custom

# application service
  games_app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    networks:
      - custom
    command: uvicorn app.main:app --host 0.0.0.0

networks:
  custom:
    driver: bridge
